package application;

import java.net.URL;
import java.util.ResourceBundle;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Label;
import javafx.scene.control.ListView;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.scene.input.KeyEvent;
import service.URLService;

public class URLController implements Initializable {
	
	private URLService urlservice;
	
	@FXML
	private TextField urlTextField;
	@FXML
	private TextArea sourceTextArea;
	@FXML
	private ListView<String> linkListView;
	@FXML
	private Label satusLAbel;

	// Event Listener on TextField[#urlTextField].onKeyPressed
	@FXML
	public void onKeyPressed(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void startAction(ActionEvent event) {
		
		urlservice.setUrlStr(urlTextField.getText());
		urlservice.restart();
	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {
		urlTextField.setText("http://www.java2s.com/");//TODO
		// URLService erzeugen
		urlservice = new URLService();
		
		sourceTextArea.textProperty().bind(urlservice.valueProperty());
		
		
	}
	
}
